name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: before install 
      run: docker build -t dasd412/docker-react-app -f Dockerfile.dev .
    
    - name: test code processing
      run: docker run -e CI=true dasd412/docker-react-app npm run test -- --coverage
      
    - name: Deploy to elastic beanstalk 
      uses: einaregilsson/beanstalk-deploy@v14 
      with: 
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        application_name: docker-react-app 
        environment_name: Dockerreactapp-env
        region: ap-northeast-2

    - name: deploy to s3 
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        AWS_S3_BUCKET: elasticbeanstalk-ap-northeast-2-235986073852
        AWS_REGION: ap-northeast-2   
        


